apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: '2020-03-16T10:50:04Z'
  labels:
    job-name: eat-job-eap
  name: eat-job-eap
  namespace: eat
  resourceVersion: '51056014'
  selfLink: /apis/batch/v1/namespaces/eat/jobs/eat-job-eap
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: eat-job-eap
      name: eat-job-eap
    spec:
      containers:
        - args:
            - clean
            - install
            - '-Deap72x'
            - '-Dstandalone'
            - '-Denforcer.skip'
            - '-DJBOSS_FOLDER=/eap/master/dist/target/jboss-eap-7.2'
            - '-DJBOSS_VERSION=7.2.7.GA-redhat-SNAPSHOT'
            - '-s'
            - /usr/share/settings-eateap.xml
          command:
            - mvn
          image: 'docker.io/panossotos/eat:eateap727'
          imagePullPolicy: IfNotPresent
          name: eat-eap-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

