apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2020-03-15T13:47:07Z'
  generation: 9
  name: eat-run-ejb
  namespace: eat
  resourceVersion: '51035340'
  selfLink: /apis/apps.openshift.io/v1/namespaces/eat/deploymentconfigs/eat-run-ejb
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    app: run-eat
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: run-eat
    spec:
      containers:
        - args:
            - clean
            - install
            - '-Deap72x'
            - '-Dstandalone'
            - '-Denforcer.skip'
            - '-DJBOSS_FOLDER=/eap/master/dist/target/jboss-eap-7.2'
            - '-DJBOSS_VERSION=7.2.7.GA-redhat-SNAPSHOT'
            - '-Dmodule=ejb'
            - '-s'
            - /usr/share/settings-eateap.xml
          command:
            - mvn
          image: 'docker.io/panossotos/eat:eateap727'
          imagePullPolicy: IfNotPresent
          name: run-eat
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
