apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: '2020-03-10T11:45:01Z'
  labels:
    controller-uid: 936a5f4b-62c4-11ea-9524-0022195774a4
    job-name: eat-job-wildfly
  name: eat-job-wildfly
  namespace: eat
  resourceVersion: '47619406'
  selfLink: /apis/batch/v1/namespaces/eat/jobs/eat-job-wildfly
  uid: 936a5f4b-62c4-11ea-9524-0022195774a4
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 936a5f4b-62c4-11ea-9524-0022195774a4
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 936a5f4b-62c4-11ea-9524-0022195774a4
        job-name: eat-job-wildfly
      name: eat-job-wildfly
    spec:
      containers:
        - args:
            - clean
            - install
            - '-Dwildfly'
            - '-Dstandalone'
            - '-Dmodule=jaxrs'
            - >-
              -DJBOSS_FOLDER=/wildfly/master/dist/target/wildfly-20.0.0.Beta1-SNAPSHOT
            - '-DJBOSS_VERSION=20.0.0.Beta1-SNAPSHOT'
            - '-s'
            - /usr/share/settings-eatwildfly.xml
          command:
            - mvn
          image: 'docker.io/panossotos/eat:wildfly2000B1'
          imagePullPolicy: IfNotPresent
          name: eat-wildfly-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  active: 1
  startTime: '2020-03-10T11:45:01Z'

