language: java
jdk:
  - oraclejdk8

sudo: required
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

install: true

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - mkdir wildfly
  - cd wildfly
  -  wget --no-check-certificate 'https://www.dropbox.com/s/qpms9i2zx5q7n1x/wildfly-13.0.0.zip?dl=0' -O wildfly.zip
  - unzip wildfly.zip
  - cd wildfly-*
  - export JBOSS_FOLDER=$PWD
  - export JBOSS_VERSION=13.0.0.Final
  - cd ../..
  - mvn -q clean install -Dwildfly-release-13.0.0.Final -Dstandalone
