language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - java -version
  - mkdir wildfly
  - cd wildfly
  - wget --no-check-certificate 'https://googledrive.com/host/0B4Gi0_mfsWRzcUdGaXJvb3VUOEU' -O wildfly.zip
  - unzip wildfly.zip
  - cd wildfly-*
  - export JBOSS_FOLDER=$PWD
  - cd ../..
  - mvn clean install -Dwildfly

